# Informasi Proyek
site_name: Cahaya Belajar Bahasa Jepang
site_url: https://arsipcahaya.github.io/BelajarBahasaJepang/
site_author: Cahaya
site_description: Catatan pribadi & sumber belajar bahasa Jepang.

# Tema Konfigurasi
theme:
  name: material
  logo: assets\images\japan.png
  favicon: assets\images\japan.png
  language: id
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - toc.follow
    # - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

  palette:
    # Mode Gelap
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Ganti ke mode terang
      primary: black
      accent: indigo
    # Mode Terang
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Ganti ke mode gelap
      primary: black
      accent: indigo

# Navigasi Menu
nav:
  - Beranda: index.md
  - Grammar:
      - Grammar:
      - Minna No Nihongo:
          - Pengantar: Grammar/Minna No Nihongo/index.md
          - Bab 1: Grammar/Minna No Nihongo/Chapter 1.md
      - Cure Dolly: Grammar/Cure Dolly/index.md
      - Yokubi: Grammar/Yokubi/index.md

# Ekstensi Markdown
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Footer
copyright: Dibuat oleh Cahaya

# Konfigurasi Tambahan
extra:
  generator: false
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:tanyacahaya@proton.me
    - icon: fontawesome/solid/gift
      link: https://yapp.ink/cahaya/tip

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - tags
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_themed: false
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
