# Informasi Proyek
site_name: Ais Belajar Bahasa Jepang
site_url: https://arsipais.github.io/BelajarBahasaJepang/
site_author: Ais
site_description: >-
  Ais Belajar Bahasa Jepang

# Repository
repo_name: arsipais/BelajarBahasaJepang
repo_url: https://github.com/arsipais/BelajarBahasaJepang

# Tema Konfigurasi
theme:
  name: material
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.footer
  palette:
    # Mode Gelap
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: indigo
    # Mode Terang
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: black
      accent: indigo

# Navigasi Menu
nav:
  - "Beranda": "index.md"
  - "Grammar":
      - "All": "Bahasa/Jepang/Grammar/index.md"
      - "Minna No Nihongo": "Bahasa/Jepang/Minna No Nihongo/index.md"
      - "Cure Dolly": "Bahasa/Jepang/Cure Dolly/index.md"
      - "Yokubi": "Bahasa/Jepang/Yokubi/index.md"

# Ekstensi Markdown
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

# Footer
copyright: Dibuat oleh Ais

# Konfigurasi Tambahan
extra:
  generator: false
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:alamatkamu@gmail.com
    - icon: fontawesome/brands/discord
      link: https://discord.gg/nY9FdajndM
    - icon: fontawesome/solid/gift
      link: https://saweria.co/Philia

extra_css:
  - stylesheets/extra.css
