# Informasi Proyek
site_name: Ais Belajar Bahasa Jepang
site_url: https://arsipais.github.io/BelajarBahasaJepang/
site_author: Ais
site_description: Catatan pribadi & sumber belajar bahasa Jepang.

# Repository
repo_name: arsipais/BelajarBahasaJepang
repo_url: https://github.com/arsipais/BelajarBahasaJepang

# Tema Konfigurasi
theme:
  name: material
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
  palette:
    # Mode Gelap
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Ganti ke mode terang
      primary: black
      accent: indigo
    # Mode Terang
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Ganti ke mode gelap
      primary: black
      accent: indigo

# Navigasi Menu
nav:
  - "Beranda": "index.md"
  - "Grammar":
      - "All": "Bahasa/Jepang/Grammar/index.md"
      - "Minna No Nihongo": "Bahasa/Jepang/Minna No Nihongo/index.md"
      - "Cure Dolly": "Bahasa/Jepang/Cure Dolly/index.md"
      - "Yokubi": "Bahasa/Jepang/Yokubi/index.md"

# Ekstensi Markdown
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Footer
copyright: Dibuat oleh Ais

# Konfigurasi Tambahan
extra:
  generator: false
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:alamatkamu@gmail.com
    - icon: fontawesome/brands/discord
      link: https://discord.gg/nY9FdajndM
    - icon: fontawesome/solid/gift
      link: https://saweria.co/Philia

extra_css:
  - stylesheets/extra.css
